import {useEffect,useRef,useState} from 'react';
import {useLocation,useNavigate} from 'react-router-dom';
import {api,Source} from '../api/client';
import {useWorkspace,useResource,ErrorBox,RichText,Sources,ConfirmDelete} from './shared';
type Action={id:string;status:string;payload:{kind:string;title:string;content?:string;when?:string;days?:number;count?:number;lesson_id?:string;item_id?:string};result:{url?:string;message?:string}};
type Session={id:string;title:string;course_id:string|null;messages:{id:string;role:string;content:string;sources:Source[];mode:string}[];actions:Action[]};
export default function Assistant(){
 const {course,refresh,notify}=useWorkspace(),location=useLocation(),navigate=useNavigate();
 const [open,setOpen]=useState(false),[expanded,setExpanded]=useState(false),[sid,setSid]=useState(''),[text,setText]=useState(''),[mode,setMode]=useState('strict'),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [tool,setTool]=useState('create_task'),[title,setTitle]=useState(''),[content,setContent]=useState('');
 const history=useResource<Session[]>(open?'/assistant/sessions':null),session=useResource<Session>(sid?'/assistant/sessions/'+sid:null);
 const generation=useRef(0),launcher=useRef<HTMLButtonElement>(null),input=useRef<HTMLTextAreaElement>(null);

 useEffect(()=>{generation.current++;setSid('');setText('');setError('');setBusy(false);setContent('');setTitle('');},[course?.id]);
 useEffect(()=>{if(open)input.current?.focus();},[open]);
 useEffect(()=>()=>{generation.current++;},[]);
 const close=()=>{setOpen(false);launcher.current?.focus();};
 const ensureSession=async()=>sid||(await api<{id:string}>('/assistant/sessions','POST',{course_id:course?.id||null})).id;
 const run=async(fn:()=>Promise<void>)=>{if(busy)return;const gen=generation.current;setBusy(true);setError('');try{await fn();}catch(e){if(gen===generation.current)setError((e as Error).message);}finally{if(gen===generation.current)setBusy(false);}};
 const send=async()=>{const gen=generation.current,id=await ensureSession();if(gen!==generation.current)return;setSid(id);await api('/assistant/sessions/'+id+'/messages','POST',{message:text,mode,page:location.pathname,request_id:crypto.randomUUID()});if(gen!==generation.current)return;setText('');session.setData(await api('/assistant/sessions/'+id));await history.refresh();};
 const propose=async()=>{const gen=generation.current,id=await ensureSession();if(gen!==generation.current)return;setSid(id);await api('/assistant/sessions/'+id+'/actions','POST',{kind:tool,title,content});if(gen!==generation.current)return;await session.refresh();session.setData(await api('/assistant/sessions/'+id));await history.refresh();setTitle('');setContent('');};
 const confirm=async(a:Action)=>{const gen=generation.current;const result=await api<{url?:string;message:string}>('/assistant/actions/'+a.id+'/confirm','POST',{confirmed:true});if(gen!==generation.current)return;await session.refresh();await refresh();window.dispatchEvent(new Event('studyforge-data-changed'));notify(result.message);if(result.url)navigate(result.url);};
 return <><button ref={launcher} className="sf-assistant-launch" aria-label="Open StudyForge assistant" aria-expanded={open} aria-controls="sf-assistant" onClick={()=>setOpen(!open)}><span className="material-symbols-outlined" aria-hidden="true">auto_awesome</span><span>Ask StudyForge</span></button>{open&&<section id="sf-assistant" className={'sf-assistant '+(expanded?'expanded':'')} role="dialog" aria-label="StudyForge assistant" onKeyDown={e=>{if(e.key==='Escape'){e.stopPropagation();close();}}}>
 <header><div><span className="sf-eyebrow">YOUR LEARNING COMPANION</span><h2>StudyForge assistant</h2><small>{course?.title||'App guide & public research'} · {location.pathname.split('/').pop()||'Dashboard'}</small></div><button className="sf-button" aria-label={expanded?'Compact assistant':'Expand assistant'} onClick={()=>setExpanded(!expanded)}>↗</button><button className="sf-button" aria-label="Close assistant" onClick={close}>×</button></header>
 <div className="sf-assistant-body"><ErrorBox message={error||session.error||history.error}/><div className="sf-toolbar"><label>Conversation<select disabled={busy} value={sid} onChange={e=>{generation.current++;setSid(e.target.value);setError('');}}><option value="">New conversation</option>{history.data?.filter(s=>s.course_id===(course?.id||null)).map(s=><option key={s.id} value={s.id}>{s.title}</option>)}</select></label><label>Mode<select value={mode} disabled={busy} onChange={e=>setMode(e.target.value)}><option value="strict">Strict course</option><option value="research">Research</option><option value="guide">App guide</option></select></label></div>
 <div className="sf-actions">{sid&&<ConfirmDelete label="assistant conversation and its action history" onDelete={()=>void run(async()=>{await api('/assistant/sessions/'+sid,'DELETE');setSid('');await history.refresh();})}/>}</div><p className="sf-muted">{mode==='research'?'Your question is sent to Wikipedia for public references and to your configured AI provider for synthesis. Course excerpts are sent only to your AI provider.':'Strict answers use this course’s indexed material. Your selected AI provider receives relevant excerpts and enabled preferences.'}</p>
 <div className="sf-assistant-messages" aria-live="polite">{!session.data?.messages.length&&<div className="sf-assistant-welcome"><span className="material-symbols-outlined" aria-hidden="true">auto_stories</span><h3>A little guidance. Your next step.</h3><p>Ask about your course, research a topic, or request a task, quiz, study plan, note, or timetable change.</p><small>Every proposed change is yours to review.</small></div>}{session.data?.messages.map(m=><article key={m.id} className={'sf-message '+m.role}><span className="sf-eyebrow">{m.role==='user'?'YOU':m.mode==='research'?'RESEARCH':'STUDYFORGE'}</span><RichText text={m.content}/><Sources sources={m.sources}/>{m.role==='assistant'&&<button className="sf-button subtle" onClick={()=>{setTool('save_note');setTitle('Saved explanation');setContent(m.content+'\n\nSources:\n'+m.sources.map(s=>(s.url||s.source_name+(s.page?' · page '+s.page:''))+'\n'+s.excerpt).join('\n\n'));}}>Use in a note</button>}</article>)}</div>
 {session.data?.actions.map(a=><article className="sf-action-review" key={a.id}><span className="sf-tag">{a.status==='pending'?'Awaiting your confirmation':a.status}</span><h3>{a.payload.kind.replaceAll('_',' ')} · {a.payload.title}</h3>{a.payload.content&&<details><summary>Review full content</summary><RichText text={a.payload.content}/></details>}{a.payload.when&&<p>Date: {a.payload.when}</p>}{a.payload.kind==='learning_plan'&&<p>Days: {a.payload.days}</p>}{a.payload.kind==='generate_quiz'&&<p>Questions: {a.payload.count}</p>}{a.payload.lesson_id&&<small>Lesson: {a.payload.lesson_id}</small>}{a.payload.item_id&&<small>Target: {a.payload.item_id}</small>}{a.payload.kind==='delete_task'&&<p className="sf-error">This permanently deletes the selected task.</p>}{a.status==='pending'&&<button disabled={busy} className={'sf-button '+(a.payload.kind==='delete_task'?'danger':'primary')} onClick={()=>void run(()=>confirm(a))}>{a.payload.kind==='delete_task'?'Confirm permanent deletion':'Confirm action'}</button>}{a.status==='pending'&&<button className="sf-button subtle" disabled={busy} onClick={()=>void run(async()=>{await api('/assistant/actions/'+a.id+'/cancel','POST');await session.refresh();})}>Decline</button>}{a.result.message&&<p>{a.result.message}</p>}{a.status==='uncertain'&&<p>Check your workspace before creating another request. This action will not be retried automatically.</p>}</article>)}
 <details open={!!content}><summary>Make a specific change</summary><p className="sf-muted">These controls also work without AI. Review the proposal before applying it.</p><form onSubmit={e=>{e.preventDefault();void run(propose);}}><label>Action<select value={tool} onChange={e=>setTool(e.target.value)}><option value="create_task">Create a task</option><option value="save_note">Save research or a note</option><option value="add_topic">Add a curriculum topic</option><option value="learning_plan">Create a 30-day study plan</option><option value="generate_quiz">Generate a quiz</option><option value="generate_pdf">Generate a PDF guide</option><option value="revision">Review weakest concepts</option></select></label><label>Title<input value={title} maxLength={180} required onChange={e=>setTitle(e.target.value)}/></label><label>Details<textarea value={content} maxLength={12000} onChange={e=>setContent(e.target.value)}/></label><button className="sf-button" disabled={busy}>Review proposed change</button></form></details></div>
 <form className="sf-assistant-compose" onSubmit={e=>{e.preventDefault();void run(send);}}><label className="sr-only" htmlFor="assistant-message">Message assistant</label><textarea id="assistant-message" ref={input} value={text} maxLength={6000} rows={2} required onChange={e=>setText(e.target.value)} placeholder="What would help you move forward?"/><button className="sf-button primary" disabled={busy||!text.trim()}>{busy?'Working…':'Send'}</button></form></section>}</>;
}
