import {useState} from 'react';
import {api} from '../api/client';
import {useResource,useAction,useWorkspace,ErrorBox,Loading} from './shared';
type Prefs={display_name:string;goals:string;language:string;depth:string;tone:string;intensity:string;learning_style:string;daily_minutes:number;preferred_hour:number;quiz_style:string;personalization:boolean;reduced_motion:boolean};
export default function Preferences(){
 const r=useResource<Prefs>('/preferences'),storage=useResource<Record<string,number>>('/storage'),activity=useResource<{id:string;created_at:string;status:string;payload:{kind:string;title:string}}[]>('/assistant/activity');const {run,busy,error}=useAction(),{notify}=useWorkspace();const [section,setSection]=useState('Profile');
 if(r.loading)return <Loading/>;if(!r.data)return <ErrorBox message={r.error}/>;const p=r.data;
 const set=(key:keyof Prefs,value:string|number|boolean)=>r.setData({...p,[key]:value});
 return <section className="sf-panel sf-preferences"><div className="sf-section-head"><div><span className="sf-eyebrow">YOUR PREFERENCES</span><h2>A workspace that fits you</h2></div><span className="sf-tag">Private to your account</span></div><div className="sf-settings-tabs" role="group" aria-label="Settings sections">{['Profile','Learning','AI behavior','Privacy','Storage','Activity'].map(s=><button key={s} aria-pressed={section===s} className={'sf-button '+(section===s?'primary':'')} onClick={()=>setSection(s)}>{s}</button>)}</div><ErrorBox message={error||r.error}/><form onSubmit={e=>{e.preventDefault();void run(async()=>{await api('/preferences','PUT',p);window.dispatchEvent(new Event('studyforge-preferences'));notify('Preferences saved for your account.');});}}>
 {section==='Profile'&&<><label>Display name<input required maxLength={80} value={p.display_name} onChange={e=>set('display_name',e.target.value)}/></label><label>Learning goals<textarea maxLength={1500} value={p.goals} onChange={e=>set('goals',e.target.value)}/></label><label>Preferred language<input required maxLength={60} value={p.language} onChange={e=>set('language',e.target.value)}/></label><label className="sf-check"><input type="checkbox" checked={p.reduced_motion} onChange={e=>set('reduced_motion',e.target.checked)}/>Reduce motion and visual depth</label></>}
 {section==='Learning'&&<><div className="sf-two-col"><label>Daily study minutes<input type="number" min={15} max={480} value={p.daily_minutes} onChange={e=>set('daily_minutes',Number(e.target.value))}/></label><label>Preferred hour (local, 0–23)<input type="number" min={0} max={23} value={p.preferred_hour} onChange={e=>set('preferred_hour',Number(e.target.value))}/></label></div><label>Study intensity<select value={p.intensity} onChange={e=>set('intensity',e.target.value)}>{['gentle','steady','intensive'].map(x=><option key={x}>{x}</option>)}</select></label><label>Learning style<select value={p.learning_style} onChange={e=>set('learning_style',e.target.value)}>{['Mixed','Theory','Practical','Project-based'].map(x=><option key={x}>{x}</option>)}</select></label><p className="sf-muted">Daily minutes shape assistant-created study tasks. Existing course schedules stay editable below. Preferred hour is guidance for planning; background notifications are not implemented.</p></>}
 {section==='AI behavior'&&<>{([['depth','Explanation depth',['brief','balanced','detailed']],['tone','Tone',['encouraging','direct','academic']],['quiz_style','Quiz format',['mixed','mcq','short_answer']]] as const).map(([key,label,options])=><label key={key}>{label}<select value={p[key]} onChange={e=>set(key,e.target.value)}>{options.map(x=><option key={x}>{x}</option>)}</select></label>)}<p className="sf-muted">Applied to requests sent through your existing provider connection. Factual grounding and explicit task instructions take precedence.</p></>}
 {section==='Privacy'&&<><label className="sf-check"><input type="checkbox" checked={p.personalization} onChange={e=>set('personalization',e.target.checked)}/>Use my saved learning preferences in AI requests</label><p>StudyForge stores your account, courses, files, conversations, preferences and action history on its server. API keys are encrypted at rest and decrypted only for your selected provider.</p><p>Your browser stores a session cookie and your active course ID. Local embeddings run on the server. AI requests send your message, relevant selected-course passages and enabled preferences to your chosen provider.</p><p>Research Mode also sends the research query to Wikipedia. It does not send uploaded documents to Wikipedia. External references are labeled separately and saved research is excluded from default Strict Course retrieval.</p><p>No hidden psychological profile or compliance certification is claimed. Manage documents and conversations in their respective pages. Delete account and bulk export are not yet available.</p></>}
 {section==='Storage'&&<><ErrorBox message={storage.error}/><div className="sf-stat-grid">{Object.entries(storage.data||{}).map(([label,count])=><div className="sf-panel" key={label}><strong className="sf-stat">{count}</strong><small>{label.replace('_',' ')}</small></div>)}</div><p className="sf-muted">Original uploads and generated files are private server files. Download important files from Knowledge and Generated Files. Deletion controls appear next to each item.</p></>}
 {section==='Activity'&&<><ErrorBox message={activity.error}/>{activity.data?.length?activity.data.map(a=><article className="sf-document-row" key={a.id}><div><strong>{a.payload.title}</strong><small>{a.payload.kind.replaceAll('_',' ')} · {new Date(a.created_at).toLocaleString()}</small></div><span className="sf-tag">{a.status}</span></article>):<p>No assistant actions yet. Proposed and applied changes will appear here.</p>}</>}
 {!['Storage','Activity'].includes(section)&&<button className="sf-button primary" disabled={busy}>Save preferences</button>}</form></section>;
}
