import {createContext,useContext,useState,useEffect,useCallback,useRef,ReactNode} from 'react';
import {Link} from 'react-router-dom';
import Markdown from 'react-markdown';
import {api,API,Course,Source,Document} from '../api/client';

export const WorkspaceContext=createContext<{course:Course|null;courses:Course[];refresh:()=>Promise<void>;notify:(text:string)=>void}>({course:null,courses:[],refresh:async()=>{},notify:()=>{}});
export const useWorkspace=()=>useContext(WorkspaceContext);
export function useResource<T>(path:string|null){
 const [data,setData]=useState<T|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 const sequence=useRef(0);
 const refresh=useCallback(async()=>{const request=++sequence.current;if(!path){setData(null);setLoading(false);return;}setLoading(true);setError('');try{const value=await api<T>(path);if(request===sequence.current)setData(value);}catch(e){if(request===sequence.current)setError((e as Error).message);}finally{if(request===sequence.current)setLoading(false);}},[path]);
 useEffect(()=>{setData(null);void refresh();return()=>{sequence.current++;};},[refresh]);return {data,setData,error,loading,refresh};
}
export function useAction(){const [busy,setBusy]=useState(false),[error,setError]=useState('');const run=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');try{await fn();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};return {busy,error,run};}
export const ErrorBox=({message}:{message?:string})=>message?<div className="sf-error" role="alert">{message}</div>:null;
export const Loading=()=> <div className="sf-loading" role="status"><span className="sf-spinner"/> Loading your workspace…</div>;
export function PageTitle({eyebrow,title,description,children}:{eyebrow?:string;title:string;description?:string;children?:ReactNode}){return <header className="sf-page-title"><div><span className="sf-eyebrow">{eyebrow||'YOUR LEARNING WORKSPACE'}</span><h1>{title}</h1>{description&&<p>{description}</p>}</div><div className="sf-actions">{children}</div></header>;}
export function Empty({title,children}:{title:string;children?:ReactNode}){return <div className="sf-empty"><span className="material-symbols-outlined">auto_stories</span><h2>{title}</h2>{children}</div>;}
export function NeedCourse(){return <Empty title="Give your curiosity a direction"><p>Create a topic to start building your personal learning library.</p><Link className="sf-button primary" to="/app/new">+ New topic</Link></Empty>;}
export function Meter({value,label}:{value:number;label:string}){return <div className="sf-meter"><div><span>{label}</span><strong>{Math.round(value)}%</strong></div><progress aria-label={label} max={100} value={value}/></div>;}
export const RichText=({text}:{text:string})=><div className="sf-prose"><Markdown>{text}</Markdown></div>;
export function Sources({sources}:{sources?:Source[]}){if(!sources?.length)return null;return <details className="sf-sources"><summary>Sources · {sources.length}</summary>{sources.map(s=><article key={s.id}><a href={API+'/documents/'+s.document_id+'/download'} target="_blank" rel="noreferrer">{s.source_name}{s.page?` · page ${s.page}`:''}</a><small>{[s.course_title,s.module_title,s.lesson_title,s.chapter,s.section,s.content_type==='note'?'Personal note':'Course source'].filter(Boolean).join(' / ')}</small><p>{s.excerpt}</p></article>)}</details>;}
export function DocumentSelector({documents,selected,setSelected}:{documents:Document[];selected:string[];setSelected:(v:string[])=>void}){return <details className="sf-source-select"><summary>{selected.length?`${selected.length} selected source(s)`:'All course sources'}</summary><p className="sf-muted">Select documents to limit the scope of this request.</p>{documents.map(d=><label className="sf-check" key={d.id}><input type="checkbox" checked={selected.includes(d.id)} onChange={e=>setSelected(e.target.checked?[...selected,d.id]:selected.filter(x=>x!==d.id))}/>{d.source_name}</label>)}</details>;}
export function Upload({courseId,onDone}:{courseId:string;onDone:()=>void}){const {busy,error,run}=useAction();return <div className="sf-upload"><label><span className="material-symbols-outlined">upload_file</span><strong>{busy?'Reading and indexing…':'Add your learning material'}</strong><span>PDF, TXT or Markdown · up to 20 MB each</span><input aria-label="Upload learning material" type="file" accept=".pdf,.txt,.md" multiple disabled={busy} onChange={e=>{const files=Array.from(e.target.files||[]);void run(async()=>{for(const file of files){const form=new FormData();form.append('file',file);await api('/courses/'+courseId+'/documents','POST',form);}onDone();});e.target.value='';}}/></label><ErrorBox message={error}/></div>;}
export function ConfirmDelete({label,onDelete}:{label:string;onDelete:()=>void}){const [confirm,setConfirm]=useState(false);return confirm?<span className="sf-actions"><button className="sf-button danger" onClick={onDelete}>Delete {label}</button><button className="sf-button" onClick={()=>setConfirm(false)}>Cancel</button></span>:<button className="sf-button subtle" onClick={()=>setConfirm(true)} aria-label={'Delete '+label}>Delete</button>;}
